### PR TITLE
DO-NOT-MERGE

### PR DESCRIPTION
**Pull request by sormuras**
Targeting origin/master to trigger GibHub Actions

### CODE REVIEW

**Comment by sormuras** [comment]
### GitHub Actions
- `Java 15-ea+23 on Linux` ❌ https://github.com/sormuras/silk/pull/2/checks?check_run_id=713934864#step:5:15

### Sors' Box
- `Java 15-ea+18-776 on Windows 10` ✔

**Comment by sormuras** [comment]
```java
	public int compareTo(Binding<?> other) {
		int res = locator.type().rawType.getCanonicalName().compareTo(
				other.locator.type().rawType.getCanonicalName());
```

`Class.getCanonicalName()` may return `null` ... is it this call? Investigating...

**Comment by jbee** [comment]
That can be changed to `getName()` that I think never returns `null`.

**Comment by sormuras** [comment]
`locator.type()` returns `null`

image

On both, `class-path` and `module-path`.

**Comment by sormuras** [comment]
Where is the `type` field of the PREDEFINED Action locator set, @jbee?

image

This field, for some reason, is assigned on Java 14 (assuming that's also the case for Java 8-13) and for at least Java 15-ea+7/8/18 ... but not longer for Java 15-ea+23/24.

**Comment by sormuras** [comment]
Fixed the build by guarding against `null`s in https://github.com/sormuras/silk/pull/2/commits/233d07637d15c956eaf5e1499e212736b08b04fe

The underlying cause is not clear to me. Record types, hidden classes?!

**Comment by jbee** [comment]
It does not make sense to me but from looking at the code I'd say the `null` comes from the `se.jbee.inject.action.ActionModule.ACTION_MIRROR` constant which would mean that 

```java
	static final Instance<ProducesBy> ACTION_MIRROR = instance(
			named(Action.class), raw(ProducesBy.class));
```

the `raw(ProducesBy.class)` somehow has `null` type. Could this be something with visibilities in java modules?

**Comment by sormuras** [comment]
No. Null happens on paths.

**Comment by jbee** [comment]
> Null happens on paths.

?

**Comment by sormuras** [comment]
Null happens on **both** paths. See my comment above. And it works on Java 14 and older 15 builds.

Dalibor will take a look tomorrow. Something definitely changed lately in java.lang.Class. With respect to records and hidden classes and more...

**Comment by robilad** [comment]
There was one change for the second preview of Records, but it only concerned itself with the compiler and ObjectStreams, afaict from https://hg.openjdk.java.net/jdk/jdk/rev/212f5084ac72 so that seems like an unlikely culprit in this case, as ObjectStreamClass does not appear to be used in this repository. Given that it's a preview feature, it should also have no effect without being explicitly enabled.

The larger change that came in between the builds was Hidden Classes https://github.com/openjdk/jdk/commit/7cc137105928ec109a29d9315565f7f49af3cf2b - which is not a preview feature. So my suggestion would be to start a thread on valhalla-dev with the details.

**Comment by sormuras** [comment]
Methinks, lambdas are involved. Still have no clue, why `ProducedBy#declaredMethods` picks up the following lambda instance. Shouldn't it be flagged synthetic and therefore ignored by

https://github.com/sormuras/silk/blob/0cb83db05df18d8afce17b1a4399094ba1c9d088/src/core/se/jbee/inject/config/ProducesBy.java#L44

That's the output of _poor-man's-debugger_...
```
instance = se.jbee.inject.config.ProducesBy$$Lambda$61/0x0000000800bb5bf0 se.jbee.inject.action.Action: || target = {* => *, [*] }
instance.name = se.jbee.inject.action.Action:
instance.type = se.jbee.inject.config.ProducesBy$$Lambda$61/0x0000000800bb5bf0
instance.type.getClass() = class se.jbee.inject.Type
instance.type.rawType = class se.jbee.inject.config.ProducesBy$$Lambda$61/0x0000000800bb5bf0
```

...statements...

```java
	public Locator(Instance<T> instance, Target target) {
		System.out.println("instance = " + instance + " || target = " + target);
		System.out.println("instance.name = " + instance.name);
		System.out.println("instance.type = " + instance.type);
		System.out.println("instance.type.getClass() = " + instance.type.getClass());
		System.out.println("instance.type.rawType = " + instance.type.rawType);
		this.instance = instance;
		this.target = target;
	}
```

...inserted here:

https://github.com/sormuras/silk/blob/0cb83db05df18d8afce17b1a4399094ba1c9d088/src/core/se/jbee/inject/Locator.java#L34-L36

**Comment by sormuras** [comment]
The `null` displayed in earlier comments stemmed from using `Class.getCanonicalName` here:

https://github.com/sormuras/silk/blob/0cb83db05df18d8afce17b1a4399094ba1c9d088/src/core/se/jbee/inject/Type.java#L432-L434

Replacing that with `Class.getName()` revealed the lamdba signature(?) `"ProducesBy$$Lambda$61/0x0000000800bb5bf0"` as printed in the previous comment.

**Comment by robilad** [comment]
The internal Class.getCanonicalName0 method has been modified to check for hidden classes and return null:

i.e.       if (isLocalOrAnonymousClass())
to         if (isHidden() || isLocalOrAnonymousClass())

so that might be the cause. 

The JEP also says that

"java.lang.invoke.LambdaMetaFactory could generate hidden nestmate classes to hold lambda bodies that access enclosing variables"

**Comment by robilad** [comment]
It's used here: https://github.com/openjdk/jdk/blob/7cc137105928ec109a29d9315565f7f49af3cf2b/src/java.base/share/classes/java/lang/invoke/InnerClassLambdaMetafactory.java#L341

**Comment by sormuras** [comment]
We're getting closer.

As `getCanonicalName()` is allowed to return `null` values, it's not okay to use its results without null-checks. Especially, when reflecting over all declared types in a class.

**Comment by sormuras** [comment]
image

**Comment by jbee** [comment]
> getCanonicalName() is allowed to return null values

Yes, using it was a mistake and it should have been `getName()`. If that fixes our problem this is definitely the right fix but in any case it should be applied.

**Comment by sormuras** [comment]
> ...  it should be applied.

Do you want me to cherry-pick the `getCanonicalName()` to `getName()` fix onto a dedicated brand with a separate PR? Or can it stay here as a single commit?

**Comment by jbee** [comment]
However you feel it is easier.

**Comment by sormuras** [comment]
As the NPE only occur on Java > 15-ea+18, I'll leave it here.

**Comment by sormuras** [comment]
Pushed eagerly -- some tests do expect canonical class names, methinks.

**Comment by sormuras** [comment]
```
   │  ├─ oneDimensionalArray ✘ expected:<[java.lang.Float[]]> but was:<[[Ljava.lang.Float;]>
   │  ├─ wildcardType ✔
   │  ├─ trippleGeneric ✔
   │  ├─ twoDimensionalArray ✘ expected:<[java.lang.Double[][]]> but was:<[[[Ljava.lang.Double;]>
   │  ├─ wildcardNestedGenericType ✔
   │  ├─ singleArrayOfGenericWithArray ✘ expected:<[java.util.List<java.lang.String[]>[]]> but was:<[<[Ljava.lang.String;>[Ljava.util.List;]>
```

@jbee -- update tests or keep non-null canonical class names in `Type`?

**Comment by jbee** [comment]
Generally update tests - however, if this is the result of `Type.toString()` the output should not change. In that case the method implementation needs to be adopted so it uses `getName()` but does special handling for arrays (and maybe also primitives). Anyhow, this is hardly your job so its fine to just ignore the tests and make a common why they need fixing - I can do that later.

**Comment by sormuras** [comment]
As I don't like failing PR's with failing tests, I re-introduced the null-check in `Type.toString(StringBuilder, boolean)` as:

```java
		String canonicalNameOrNull = rawType.getCanonicalName();
		String name = canonicalName
			? canonicalNameOrNull != null
				? canonicalNameOrNull
				: rawType.getName()
			: rawType.getSimpleName();
```

With this, all current tests are green and it'll be up to you to implement a special handling later.

**Comment by jbee** [comment]
@sormuras Can you please create an issue so I don't forget to do that?

**Comment by sormuras** [comment]
Sure. I'll create an umbrella issue as well that keeps track of the "ant-to-bach" move. This PR is basically ready. Only API documentation, some modular clean up, and deployment preparation are missing. I'd like to to tackle those in separate issues/PRs ... to not overload this one. D'accord?

**Comment by jbee** [comment]
What would be needed to get the CI you run here running for silk repo?

**Comment by sormuras** [comment]
I guess, merge the `.github/...` related stuff...

**Pull request merged**
